### GET request to read all users
GET http://localhost:3000/api/v2/users

### POST request to create a new user 
POST http://localhost:3000/api/v2/users
Content-Type: application/json

{
    "username": "homes",
    "email": "homes@example.com",
    "password": "12345678",
    "role": "admin"
}

### DELETE request to delete a user
DELETE http://localhost:3000/api/v1/users/4

### Post Login a user
POST http://localhost:3000/api/v2/users/auth/cookie/login
Content-Type:  application/json

{
    "email": "homes@example.com",
    "password": "12345678"
}

### Post Logout a user
POST http://localhost:3000/api/v2/users/auth/cookie/logout

### GET Check user authentication
GET http://localhost:3000/api/v2/users/auth/cookie/me
